server:
  port: 8082
spring:
  kafka:
    consumer:
      bootstrap-servers: "localhost:39092,localhost:29092"
      group-id: stream
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  output:
    ansi:
      enabled: "ALWAYS"
message:
  topic:
    name: "ev_kafka_local"